---
- hosts: all
  become: yes
  vars:
    rbenv_user: vagrant
    rbenv_root: ~/.rbenv
    ruby_version: 3.1.4

  pre_tasks:
    - apt: update_cache=true cache_valid_time=3600

  tasks:
  - name: install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - autoconf
      - patch
      - build-essential
      - rustc
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev

  - block:
    - name: rbenv
      git: 
        repo: https://github.com/rbenv/rbenv.git
        dest: "{{ rbenv_root }}"

    - name: plugins
      git:
        repo: "{{ item.url }}"
        dest: "{{ rbenv_root }}/plugins/{{ item.name }}"
      with_items:
        - { name: 'ruby-build', url: 'https://github.com/rbenv/ruby-build.git' }
        - { name: 'rbenv-china-mirror', url: 'https://github.com/andorchen/rbenv-china-mirror.git' }
        - { name: 'rbenv-vars', url: 'https://github.com/rbenv/rbenv-vars.git' }
    
    - name: load rbenv
      lineinfile:
        path: ~/.bash_profile
        line: 'eval "$({{ rbenv_root }}/bin/rbenv init - bash)"'
        create: true

    - name: "install ruby"
      shell: $0 -lc "~/bin/rbenv install --skip-existing {{ ruby_version }}"
      args:
        creates: "{{ rbenv_root }}/versions/{{ ruby_version }}"
      environment:
        RUBY_CONFIGURE_OPTS: --disable-install-doc --disable-install-rdoc

    become: true
    become_user: "{{ rbenv_user }}"